# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-28 06:13
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('VicaraBackendAPI', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employeeID', models.CharField(max_length=128, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('location', models.CharField(max_length=128)),
                ('project_code', models.CharField(max_length=128)),
                ('date', models.DateField(default=datetime.date.today)),
                ('start_time', models.TimeField(default=django.utils.timezone.now)),
                ('end_time', models.TimeField(default=django.utils.timezone.now)),
                ('break_hour', models.TimeField()),
                ('work_hour', models.TimeField()),
                ('approval_status', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=255)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
