# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-17 00:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VicaraBackendAPI', '0002_timesheet'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProejctMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('psp_element', models.CharField(max_length=128, unique=True)),
                ('project_name', models.CharField(max_length=128)),
                ('start_date', models.DateField(default=datetime.date.today)),
                ('end_date', models.DateField(default=datetime.date.today)),
                ('fixed_price', models.BooleanField()),
            ],
        ),
    ]
