# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-17 00:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VicaraBackendAPI', '0003_proejctmaster'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProejctMaster',
            new_name='ProjectMaster',
        ),
    ]
