# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-17 23:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VicaraBackendAPI', '0004_auto_20171216_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesheet',
            name='employeeID',
            field=models.CharField(max_length=128),
        ),
    ]
