# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-18 03:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('VicaraBackendAPI', '0005_auto_20171217_1637'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=128)),
                ('psp_element_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VicaraBackendAPI.ProjectMaster', to_field='psp_element')),
                ('user_email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='email')),
            ],
        ),
    ]
